/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import HuffmanAlgorithm.Huffman;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author molayab
 */
public class MainWindow extends javax.swing.JFrame {

    private final String[] cols = {"Caracter", "ASCII", "Codigo"};

    private DefaultTableModel model;
    private Huffman huffman;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        model = new DefaultTableModel();

        for (String col : cols) {
            model.addColumn(col);
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        fileField = new javax.swing.JTextField();
        compileButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        input_field = new javax.swing.JTextArea();
        isFileField = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        charset = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        output_field = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Algoritmo de Huffman");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada"));

        fileField.setText("Sin archivo...");

        compileButton.setText("Cargar");
        compileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileButtonActionPerformed(evt);
            }
        });

        input_field.setColumns(20);
        input_field.setRows(5);
        input_field.setText("Hola mundo .... esto es una prueba de huffman... :)");
        jScrollPane2.setViewportView(input_field);

        isFileField.setText("Usar archivo");

        jButton1.setText("Decodificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        charset.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ASCII", "UNICODE" }));
        charset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charsetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(fileField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isFileField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(charset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compileButton)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compileButton)
                    .addComponent(isFileField)
                    .addComponent(jButton1)
                    .addComponent(charset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Salida"));

        output_field.setColumns(20);
        output_field.setRows(5);
        jScrollPane3.setViewportView(output_field);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel5);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Codigo", jPanel1);

        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mapa de codigos", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void compileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compileButtonActionPerformed
        // TODO add your handling code here
        if (!isFileField.isSelected()) {
            try {
                switch (charset.getSelectedIndex()) {
                case 0:
                    //ASCII
                    huffman = new Huffman(input_field.getText(), Huffman.ASCII);
                    break;
                case 1:
                case 2:
                    //UNICODE
                    huffman = new Huffman(input_field.getText(), Huffman.UNICODE);
                    break;
                default:
                    break;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "La codificacion (charset)"
                        + " no es valida para los caracteres ingresados.");
            }
            
            
        } else {
            JDialog dialog = new JDialog((JDialog) null, "Leyendo archivo...");

            JProgressBar progress = new JProgressBar(0, 100);
            progress.setPreferredSize(new Dimension(175, 20));
            progress.setString("Leyendo...");
            progress.setStringPainted(true);
            progress.setValue(0);

            JPanel center = new JPanel();
            center.add(progress);

            dialog.getContentPane().add(center, BorderLayout.CENTER);
            dialog.pack();
            dialog.setVisible(true);

            dialog.setLocationRelativeTo(null);
            dialog.setLocation(550, 25);
            dialog.toFront();

            File file = new File(fileField.getText());

            try {
                FileInputStream fis = new FileInputStream(file);
                StringBuffer buffer = new StringBuffer();

                int chunk;
                long size = file.length();

                while ((chunk = fis.read()) != -1) {
                    buffer.append((char) chunk);

                    progress.setValue((int) (((double) chunk / (double) size) * 100));
                }

                dialog.dispose();

                input_field.setText(buffer.toString());

                huffman = new Huffman(buffer.toString());

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
            }
        }

        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }

        if (huffman != null) {
            huffman.compress();

            output_field.setText(huffman.getCode());

            Map<Character, String> data = huffman.getHashes();

            Iterator it = data.entrySet().iterator();

            while (it.hasNext()) {
                Map.Entry pairs = (Map.Entry) it.next();

                Character charStr = (Character) pairs.getKey();

                String[] value = {charStr.toString(),
                    "0x" + Integer.toHexString((int) charStr.charValue()),
                    (String) pairs.getValue()};

                model.addRow(value);
                it.remove();
            }

            model.fireTableDataChanged();
        }
    }//GEN-LAST:event_compileButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ret = huffman.decode(input_field.getText());
        
        if (ret.equals("")) {
            JOptionPane.showMessageDialog(this, "Codigo no valido");
        } 
        
        output_field.setText(ret);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void charsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charsetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charsetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox charset;
    private javax.swing.JButton compileButton;
    private javax.swing.JTextField fileField;
    private javax.swing.JTextArea input_field;
    private javax.swing.JCheckBox isFileField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea output_field;
    // End of variables declaration//GEN-END:variables
}
